- name: Configure Docker VMS
  hosts: all
  become: yes
  tasks:
    - name: Ensure Python is installed
      raw: apt-get update && apt-get install -y python3
      changed_when: false
    
    - name: Install useful packages
      apt: 
        name:
          - htop
          - curl
        state: present
        update_cache: yes
    - name: Add devuser to sudo group
      user:
        name: devuser
        groups: sudo
        append: yes 
        shell: /bin/bash 
        create_home: yes
    
    - name: Copy SSH public key
      copy:
        src: ./files/id_rsa.pub 
        dest: /home/devuser/.ssh/authorized_keys
        owner: devuser 
        mode: 0600

    