- hosts: localhost
  connection: local 
  gather_facts: no
  tasks:
    - name: Wait for pods to be ready
      command: kubectl wait --for=condition=Ready pods --all -n opentofu-ansible --timeout=300s
      register: wait_result

    - name: Run Ansible Playbooks
      command: > 
        ansible-playbook -i {{ lookup{'env', 'ANSIBLE_DIR') }}/k8s_inventory.py 
        {{ lookup('env','ANSIBLE_DIR') }}/playbooks/{{ items }}.yaml
      loop:
        - ubuntu
        - centos
      register: ansible_result
    - name: Display Ansible result
      debug:
        var: ansible_result.stdout_lines
    - name: Save Ansible logs to MySQL
      mysql_query:
        login_host: mysql 
        login_user: root
        login_password: u7fes52wd3
        db: semaphore_db
        query: > 
          INSERT INTO ansible_logs (playbook, log_data, created_at) VALUES (%s, %s, NOW())
        positional_args:
          - "{{ item }}"
          - "{{ ansible_result.stdout }}"
      loop:
        - ubuntu
        - centos
      ignore_errors: yes
