- hosts: localhost
  connection: localhost
  gather_facts: no
  tasks:
    - name: Run OpenTofu init
      command: tofu init
      args:
        chdir: "{{ lookup('env', 'OPENTOFU_DIR') }}"
      register: init_result
    - name: Display init result
      debug: 
        var: init_result.stdout_lines
    - name: Run OpenTofu apply
      command: tofu apply -auto-approve
      args: 
        chdir: "{{ lookup('env', 'OPENTOFU_DIR') }}"
      register: apply_result

    - name: Display apply result
      debug:
        var: apply_result.stdout_lines

    - name: Save OpenTofu state to MySQL
      mysql_query:
        login_host: mysql 
        login_user: root
        login_password: u7fes52wd3
        db: semaphore_db
        query: > 
          INSERT INTO tofu_states (state_data, created_at) VALUES (%s, NOW())
        positional_args:
          - "{{ lookup('file', lookup('env', 'OPENTOFU_DIR') + '/terraform.tfstate') }}"
      ignore_errors: yes
