services:
    semaphore_db:
        image: mysql:8
        environment:
            MYSQL_USER: semaphore
            MYSQL_PASSWORD: u7fes52wd3
            MYSQL_DATABASE: semaphore
            MYSQL_RANDOM_ROOT_PASSWORD: yes
        volumes:
            - semaphore_mysql:/var/lib/mysql
        networks:
            - semaphore_network
    semaphore:
        ports:
            - 3000:3000
        depends_on:
            - semaphore_db
        image: semaphoreui/semaphore:v2.15.0
        environment:
            SEMAPHORE_DB_DIALECT: mysql
            SEMAPHORE_DB_HOST: semaphore_db
            SEMAPHORE_DB_NAME: semaphore
            SEMAPHORE_DB_USER: semaphore
            SEMAPHORE_DB_PASS: u7fes52wd3
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: changeme
            SEMAPHORE_ADMIN_NAME: Admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
            SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
        volumes:
            - ~/.kube:/home/semaphore/.kube
            - ~/.ssh:/home/semaphore/.ssh
            - ../opentofu:/tmp/opentofu
            - .../ansible:/tmp/ansible
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
        networks:
            - semaphore_network
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
    semaphore_mysql:
networks:
    semaphore_network: {driver: "bridge"}