# centos specific vars
ansible_python_interpreter: /usr/bin/python3
ansible_os_family: RedHat
package_manager: yum 

#packages to install
os_packages:
  - python3-pip 
  - epel-release
  - curl
  - wget
  - vim
  - net-tools
  - htop
  - tree
  - git

# service config
services_to_enable:
  - sshd

profile_path: /etc/profile.d/custom.sh
bash_profile_path: /root/.bashrc

mysql_client_package: mysql

custom_env_vars:
  PATH: "$PATH:/usr/local/bin"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"

